/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.3.0
 *
 * Project: 'USBD_HID_MouseKeyboard.Debug+Debug' 
 * Target:  'Debug+Debug' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "M031Series.h"



#endif /* RTE_COMPONENTS_H */
